import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const routes = {
  '/': 'home', '/about': 'about', '/product': 'product', '/pricing': 'pricing', '/faq': 'faq', '/contact': 'contact'
}

const features = [
  ['01', 'Your storefront, your rules.', 'Pick a theme, connect your domain, and make your first sale without waiting on a developer.', 'store'],
  ['02', 'The work, in one calm place.', 'Products, categories, orders, customers, and analytics in a dashboard built for business owners.', 'dashboard'],
  ['03', 'Sell the way your customers shop.', 'Payment gateways, WhatsApp product management, and SEO-ready content are part of the flow.', 'connect']
]

function navigate(path) { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')) }

function Logo() { return <a className="logo" href="/" onClick={e => { e.preventDefault(); navigate('/') }}><span className="logo-mark">S</span><span>SYMKART</span></a> }

function Header({ dark = false }) {
  const [open, setOpen] = useState(false)
  const links = [['About', '/about'], ['SYMKART', '/product'], ['Pricing', '/pricing'], ['FAQ', '/faq'], ['Contact', '/contact']]
  return <header className={`site-header ${dark ? 'header-dark' : ''}`}>
    <Logo />
    <nav className={open ? 'nav-open' : ''} aria-label="Primary navigation">
      {links.map(([label, path]) => <a key={path} href={path} onClick={e => { e.preventDefault(); setOpen(false); navigate(path) }}>{label}</a>)}
    </nav>
    <div className="header-actions"><a className="text-link hide-mobile" href="/contact" onClick={e => { e.preventDefault(); navigate('/contact') }}>Sign in</a><a className="button button-dark" href="/contact" onClick={e => { e.preventDefault(); navigate('/contact') }}>Start free trial <span>↗</span></a></div>
    <button className="menu-button" aria-label="Toggle menu" onClick={() => setOpen(!open)}>{open ? '×' : '☰'}</button>
  </header>
}

function Footer() { return <footer className="footer"><div className="footer-main"><div><Logo /><p className="footer-note">Simple tools for serious commerce.</p></div><div className="footer-links"><div><p className="footer-label">Explore</p><a href="/product" onClick={e => { e.preventDefault(); navigate('/product') }}>SYMKART</a><a href="/pricing" onClick={e => { e.preventDefault(); navigate('/pricing') }}>Pricing</a><a href="/faq" onClick={e => { e.preventDefault(); navigate('/faq') }}>FAQ</a></div><div><p className="footer-label">Company</p><a href="/about" onClick={e => { e.preventDefault(); navigate('/about') }}>About us</a><a href="/contact" onClick={e => { e.preventDefault(); navigate('/contact') }}>Contact</a><a href="https://symphozen.com/products">Symphozen Labs ↗</a></div></div></div><div className="footer-bottom"><span>© 2026 Symphozen Labs. All rights reserved.</span><span>Built for businesses that are going places.</span></div></footer> }

function CtaBand() { return <section className="cta-band"><div><p className="eyebrow mint">READY WHEN YOU ARE</p><h2>Your next chapter<br /><em>starts here.</em></h2></div><div className="cta-band-side"><p>Launch your store in the next 14 days, with room to grow after that.</p><a className="button button-mint" href="/contact" onClick={e => { e.preventDefault(); navigate('/contact') }}>Start free trial <span>↗</span></a></div></section> }

function BrowserMockup() { return <div className="browser-wrap"><div className="browser"><div className="browser-top"><div className="traffic"><i /><i /><i /></div><span className="browser-url">app.symkart.com / overview</span><span className="browser-dot">•••</span></div><div className="app-body"><aside><div className="app-brand"><span className="logo-mark">S</span><b>SYMKART</b></div><span className="side-active">Overview</span><span>Products</span><span>Orders</span><span>Customers</span><span>Analytics</span><span>Settings</span><div className="side-bottom">S<span>Support center</span></div></aside><main className="app-main"><div className="app-heading"><div><small>MONDAY, SEPTEMBER 07</small><h3>Good morning, Ananya.</h3></div><div className="avatar">A</div></div><div className="metrics"><div><small>NET SALES</small><strong>₹ 1,84,240</strong><span className="up">↑ 18.4%</span></div><div><small>ORDERS</small><strong>128</strong><span className="up">↑ 12.8%</span></div><div><small>VISITORS</small><strong>8,492</strong><span className="up">↑ 26.1%</span></div></div><div className="chart-card"><div className="chart-head"><b>Sales overview</b><span>Last 7 days⌄</span></div><div className="chart"><div className="chart-grid"><i /><i /><i /><i /></div><svg viewBox="0 0 560 160" preserveAspectRatio="none" aria-label="Sales growth chart"><path d="M0 136 C40 140, 48 112, 86 120 S140 92, 170 110 S220 90, 260 96 S300 55, 340 68 S400 40, 440 52 S500 18, 560 24" fill="none" stroke="#b8f7d0" strokeWidth="4" strokeLinecap="round" /><path d="M0 136 C40 140, 48 112, 86 120 S140 92, 170 110 S220 90, 260 96 S300 55, 340 68 S400 40, 440 52 S500 18, 560 24 V160 H0Z" fill="url(#fade)" opacity=".4" /><defs><linearGradient id="fade" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#b8f7d0" /><stop offset="1" stopColor="#b8f7d0" stopOpacity="0" /></linearGradient></defs></svg></div></div></main></div></div><div className="browser-shadow" /></div> }

function Home() { return <><Header dark /><main className="home"><section className="hero"><div className="hero-copy"><p className="eyebrow mint">COMMERCE, WITHOUT THE COMPLEXITY</p><h1>Own your store.<br /><em>Not a subscription.</em></h1><p className="hero-sub">SYMKART gives growing businesses the simplest way to launch, run, and grow online.</p><div className="button-row"><a className="button button-mint" href="/contact" onClick={e => { e.preventDefault(); navigate('/contact') }}>Start free trial <span>↗</span></a><a className="button button-outline" href="/product" onClick={e => { e.preventDefault(); navigate('/product') }}>See how it works <span>↓</span></a></div><div className="hero-meta"><span><b>14 days</b> to try it free</span><span><b>5 themes</b> to make it yours</span></div></div><div className="hero-visual"><BrowserMockup /><div className="hero-stamp"><span>Made for</span><strong>business<br />owners.</strong></div></div></section><section className="signal"><p>Everything you need to make online feel easy.</p><div className="signal-line"><span>01 — YOUR STORE</span><span>02 — YOUR BUSINESS</span><span>03 — YOUR GROWTH</span></div></section><section className="feature-intro"><p className="eyebrow">ONE PLATFORM. LESS FRICTION.</p><h2>The busywork gets<br />out of your way.</h2><p className="intro-copy">You know your business. SYMKART gives you the tools to run it beautifully, without learning a new language first.</p></section><section className="feature-list">{features.map(([n, title, text, type]) => <article className={`feature-row feature-${type}`} key={n}><span className="feature-num">{n}</span><div className="feature-art" aria-hidden="true">{type === 'store' ? <><div className="art-store-top">yourbrand<span>⌁</span></div><div className="art-store-body"><b>Good things<br />take time.</b><i /></div></> : type === 'dashboard' ? <><div className="art-dash-nav" /><div className="art-dash-grid"><i /><i /><i /><i /><i /><i /></div></> : <><div className="orbit orbit-one" /><div className="orbit orbit-two" /><span className="art-connect">connect<br />everything</span></>}</div><div className="feature-copy"><h3>{title}</h3><p>{text}</p><a href="/product" onClick={e => { e.preventDefault(); navigate('/product') }}>Explore SYMKART <span>↗</span></a></div></article>)}</section><section className="themes-strip"><div className="themes-heading"><p className="eyebrow mint">FIVE WAYS TO LOOK THE PART</p><h2>A store that feels<br /><em>like you.</em></h2><a className="text-link light" href="/product" onClick={e => { e.preventDefault(); navigate('/product') }}>Explore the themes <span>↗</span></a></div><div className="theme-tiles"><div className="theme-tile tile-fashion"><span>01</span><b>Modern<br />Minimal</b></div><div className="theme-tile tile-luxury"><span>02</span><b>Premium<br />Goods</b></div><div className="theme-tile tile-local"><span>03</span><b>Local<br />Commerce</b></div></div></section><CtaBand /></main><Footer /></> }

function PageHero({ eyebrow, title, children }) { return <section className="page-hero"><p className="eyebrow mint">{eyebrow}</p><h1>{title}</h1>{children && <p>{children}</p>}</section> }

function About() { return <><Header /><main><PageHero eyebrow="THE PEOPLE BEHIND THE PRODUCT" title={<>Built for the<br /><em>long game.</em></>}>SYMKART is a product from Symphozen Labs, a technology company building focused tools for the next generation of businesses.</PageHero><section className="about-story"><div className="about-number">01</div><div><h2>Good software should<br />make room for <em>good work.</em></h2><p>Small businesses don't need more noise. They need technology that respects their time, gives them control, and helps them show up confidently online.</p><p>That is why we are building SYMKART: a simpler, more considered way to own your commerce presence.</p><a className="button button-dark" href="https://symphozen.com/products">Meet Symphozen Labs <span>↗</span></a></div><div className="about-visual"><span>SYMPHOZEN<br />LABS</span><i>✳</i></div></section><CtaBand /></main><Footer /></> }

function Product() { return <><Header /><main><PageHero eyebrow="THE SYMKART PLATFORM" title={<>Everything your<br /><em>store needs.</em></>}>A calm, capable toolkit for launching and operating your online business — from first product to everyday growth.</PageHero><section className="capability-grid">{[['01','Storefronts','Choose from five professional themes. Make the first impression yours.'],['02','Operations','Products, categories, orders, customers — one clear dashboard.'],['03','Momentum','Analytics, SEO-friendly descriptions, and content support to keep moving.'],['04','Connections','Payment gateways, custom domains, and WhatsApp product management.']].map(([n,t,d]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><div className="cap-line" /></article>)}</section><section className="themes-detail"><div className="themes-detail-copy"><p className="eyebrow">CHOOSE YOUR STARTING POINT</p><h2>Five themes.<br />One <em>you.</em></h2><p>Start with a foundation that fits your business today. Switch direction as you grow.</p></div><div className="theme-stack"><div className="stack-card stack-one"><span>MODERN MINIMAL</span><b>Less, but better.</b></div><div className="stack-card stack-two"><span>FASHION / LIFESTYLE</span><b>Make an entrance.</b></div><div className="stack-card stack-three"><span>LOCAL BUSINESS</span><b>Close to home.</b></div></div></section><section className="whatsapp-band"><div className="wa-mark">⌁</div><div><h2>Manage products<br />where conversations <em>happen.</em></h2><p>Add and update products through WhatsApp when that is the fastest way to get things done.</p></div></section><CtaBand /></main><Footer /></> }

function Pricing() { return <><Header /><main><PageHero eyebrow="PLANS THAT GROW WITH YOU" title={<>Start small.<br /><em>Think big.</em></>}>Try SYMKART free for 14 days. When you are ready, choose the plan that fits the way you work.</PageHero><section className="pricing-grid"><article className="price-card"><div className="price-top"><span className="price-label">FOR SMALL BUSINESSES</span><h2>Smart</h2><p>Everything you need to get your first store online.</p><div className="price">₹ 999 <small>/ month</small></div><a className="button button-dark wide" href="/contact" onClick={e => { e.preventDefault(); navigate('/contact') }}>Start free trial <span>↗</span></a></div><div className="price-features"><b>Includes</b><span>Up to 50 products</span><span>Up to 10 categories</span><span>5 media assets per product</span><span>5 MB media per product</span><span>14-day free trial</span></div></article><article className="price-card enterprise"><div className="price-top"><span className="price-label">FOR GROWING OPERATIONS</span><h2>Enterprise</h2><p>More room, more scale, and a plan built around your business.</p><div className="price custom">Let’s talk</div><a className="button button-mint wide" href="/contact" onClick={e => { e.preventDefault(); navigate('/contact') }}>Request pricing <span>↗</span></a></div><div className="price-features"><b>Includes</b><span>Unlimited products</span><span>Unlimited categories</span><span>5 media assets per product</span><span>10 MB media per product</span><span>Advanced scalability</span></div></article></section><section className="pricing-note"><span>01</span><p>Every plan includes self-service onboarding. Need a hand? Ask us about our optional assisted store setup service.</p></section></main><Footer /></> }

const faqs = [['What is SYMKART?', 'SYMKART is a multi-tenant ecommerce SaaS platform that helps businesses create and operate their own online store.'],['Can I try SYMKART before paying?', 'Yes. Every new business can start with a 14-day free trial and explore the product before choosing a plan.'],['What can I customize?', 'You can choose your storefront theme, add your own products and categories, connect a custom domain, and configure supported payment gateways.'],['Do I need technical experience?', 'No. SYMKART is designed for business owners. The onboarding journey is self-service, with optional assisted setup if you prefer hands-on support.'],['Can I change my theme later?', 'Yes. You can choose from the five initial themes and change direction as your business evolves.'],['What is the difference between Smart and Enterprise?', 'Smart is designed for smaller catalogs. Enterprise offers unlimited products and categories, more media capacity per product, and advanced scalability through enquiry.']]
function Faq() { const [active, setActive] = useState(0); return <><Header /><main><PageHero eyebrow="QUESTIONS, ANSWERED" title={<>Clarity is<br /><em>kindness.</em></>}>The essentials, in plain language. If your question is not here, we would love to hear it.</PageHero><section className="faq-list">{faqs.map(([q,a],i) => <button className={`faq-item ${active === i ? 'active' : ''}`} onClick={() => setActive(active === i ? -1 : i)} key={q}><span className="faq-q">{q}</span><span className="faq-toggle">{active === i ? '−' : '+'}</span>{active === i && <span className="faq-a">{a}</span>}</button>)}</section><CtaBand /></main><Footer /></> }

function Contact() { const [sent, setSent] = useState(false); const [mode, setMode] = useState('trial'); return <><Header /><main><PageHero eyebrow="LET’S BUILD SOMETHING REAL" title={<>Your store<br /><em>starts here.</em></>}>Start a 14-day free trial, or tell us what you need from an Enterprise plan. We will take it from there.</PageHero><section className="contact-layout"><div className="contact-aside"><div className="contact-toggle"><button className={mode === 'trial' ? 'selected' : ''} onClick={() => setMode('trial')}>Start free trial</button><button className={mode === 'enterprise' ? 'selected' : ''} onClick={() => setMode('enterprise')}>Enterprise enquiry</button></div><h2>{mode === 'trial' ? 'A simpler store is  a few good clicks away.' : 'Let’s make room for what’s next.'}</h2><p>{mode === 'trial' ? 'No credit card required. Set up your store, choose a theme, and see how it feels.' : 'Tell us about your business and we will shape the right onboarding journey for you.'}</p><div className="contact-detail"><span>EMAIL</span><b>hello@symphozen.com</b></div><div className="contact-detail"><span>COMPANY</span><b>Symphozen Labs</b></div></div><form className="contact-form" onSubmit={e => { e.preventDefault(); setSent(true) }}>{sent ? <div className="success"><span>✓</span><h2>We have your note.</h2><p>Thanks for reaching out. We will be in touch soon.</p><button type="button" className="button button-dark" onClick={() => setSent(false)}>Send another <span>↗</span></button></div> : <><div className="form-row"><label>First name<input required name="firstName" placeholder="Ananya" /></label><label>Last name<input required name="lastName" placeholder="Sharma" /></label></div><label>Work email<input required type="email" name="email" placeholder="you@yourbusiness.com" /></label><label>Business name<input required name="business" placeholder="Your business" /></label>{mode === 'enterprise' && <label>Tell us a little more<textarea name="message" rows="4" placeholder="What are you building?"></textarea></label>}<button className="button button-dark wide" type="submit">{mode === 'trial' ? 'Create my trial' : 'Send enquiry'} <span>↗</span></button><p className="form-note">By continuing, you agree to be contacted about SYMKART.</p></>}</form></section></main><Footer /></> }

function App() { const [path, setPath] = useState(window.location.pathname); useEffect(() => { const f = () => setPath(window.location.pathname); window.addEventListener('popstate', f); return () => window.removeEventListener('popstate', f) }, []); const page = routes[path] || 'home'; return page === 'home' ? <Home /> : page === 'about' ? <About /> : page === 'product' ? <Product /> : page === 'pricing' ? <Pricing /> : page === 'faq' ? <Faq /> : <Contact /> }

createRoot(document.getElementById('root')).render(<App />)
